[CI]Allow more network downtime in tempest
We observed that test_server_connectivity_live_migration fails with
AssertionError: 5.2 not less than or equal to 5.0 : Downtime of 5.2 seconds is higher than expected '5.0'
intermittently. This is understood to be due to slow environment so this
PR bumps the timeout.